spring:
  application:
    name: compliments

server:
  port: 8100

greetings:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090,localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000
